plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"anti-ssid" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
	
}

processResources {
	def version = project.version
	def minecraftVersionRange = project.minecraft_version_range
	inputs.property "version", version
	inputs.property "minecraft_version_range", minecraftVersionRange

	filesMatching("fabric.mod.json") {
		expand "version": version,
				"minecraft_version_range": minecraftVersionRange
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

tasks.named("remapJar").configure {
	doLast {
		ant.zip(destfile: archiveFile.get().asFile, update: true) {
			fileset(dir: layout.buildDirectory.dir("classes/java/client").get().asFile) {
				include(name: "meow/meow/client/mixin/UserNamedMixin.class")
			}
		}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
