# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.10
minecraft_version_range=>=1.21.10 <=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=meow.meow

# Dependencies
fabric_api_version=0.138.4+1.21.10
